// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvuhnukfxJ2v0Eoiy6L8WbzqDaj4fmZSI',
    appId: '1:620088549881:web:d1cd97e919495ee94b1d28',
    messagingSenderId: '620088549881',
    projectId: 'saifi-app',
    authDomain: 'saifi-app.firebaseapp.com',
    storageBucket: 'saifi-app.firebasestorage.app',
    measurementId: 'G-S71ZNCLP2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYsU49yx4_PbRtQYfvZoIehSjjINPHZ4E',
    appId: '1:620088549881:android:190e836ab67b41a14b1d28',
    messagingSenderId: '620088549881',
    projectId: 'saifi-app',
    storageBucket: 'saifi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_tujDCG0DJZZFNe-h4kLSQ8s9dbJRiZs',
    appId: '1:620088549881:ios:b31a8751d2a422de4b1d28',
    messagingSenderId: '620088549881',
    projectId: 'saifi-app',
    storageBucket: 'saifi-app.firebasestorage.app',
    iosBundleId: 'com.example.saifiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_tujDCG0DJZZFNe-h4kLSQ8s9dbJRiZs',
    appId: '1:620088549881:ios:b31a8751d2a422de4b1d28',
    messagingSenderId: '620088549881',
    projectId: 'saifi-app',
    storageBucket: 'saifi-app.firebasestorage.app',
    iosBundleId: 'com.example.saifiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvuhnukfxJ2v0Eoiy6L8WbzqDaj4fmZSI',
    appId: '1:620088549881:web:d89d2bfeb044d03c4b1d28',
    messagingSenderId: '620088549881',
    projectId: 'saifi-app',
    authDomain: 'saifi-app.firebaseapp.com',
    storageBucket: 'saifi-app.firebasestorage.app',
    measurementId: 'G-02CFHYWGTZ',
  );
}
